# this is basic gh actions workflow

name: Github actions Maven Build

on:
  push: 
    branches:  [ master ]
jobs:
  # this workflow contains single job called build
  build:  
    # type of runner  that job will run on
    runs-on: ubuntu-latest

    #steps represent sequence of task
    steps:
      # chesk out your repo under $GITHUB_WORKSPACE, so job can access it
      - name: Step 1 Check out main branch from Github
        uses: actions/checkout@v2

    # Runs a single command using runners shell
      - name: Step 2 Set up JDK 1.8
        uses:  actions/setup-java@v1
        with:
          java-vesion: 1.8

      - name: Step 3 HAve Github Actions build Maven Project
        run:  mvn -8 package --file pom.xml

      - name: Step 4 List the current directory
        run: ls-a

      - name:  Step 5 What is the target folder
        run: |
          cd target
          ls -a
